### ISSUE TITLE
Create "Tour of Heroes" app

### ISSUE THREAD

**Issue by sc0tt5** [sc0tt5/nx-demo#40]
Add John Papa's Tour of Heroes demo app to demo how this would work in NX Mono-repo with SSR, etc.
https://github.com/johnpapa/heroes-angular

**Tasks**
- [x] Create hero editor in shared libs
- [x] Build update functionality (store + nestjs)
- [x] Build delete functionality (store + nestjs)
- [x] Implement router state store
- [x] Add missing logos
- [x] Build create functionality (store + nestjs)
- [x] Create dashboard container component
- [x] Create/reuse loading indicator in shared libs
- [x] Move styles from app scss to each component
- [x] Fix/enhance theme

**ToDo (to backlog):**
* SSR server import
* Unit tests (see issue 7)
* Customizable theme
* Add component-store to form component, etc. (https://ngrx.io/guide/component-store/comparison)
* Update README with steps on how to build/run ToH (https://github.com/ionic-team/ionic-conference-app)
* Explore Nx tools/* workspace generators, lint checks, etc., developer workflow, etc.

**Maybe (to backlog):**
- Implement a UI State in store
- Use alternative to Bulma?
- Advanced NGRX example using normalizr (https://github.com/paularmstrong/normalizr)

**Comment by sc0tt5** [comment]
Still WIP, but will be a good starting point for the next version
